#!/bin/sh

echo "• Aggiornamento del sistema in corso..."
yay -Syyu

echo

orphans=$(pacman -Qdtq)
if [ -n "$orphans" ]; then
  echo "• Rimozione pacchetti orfani..."
  sudo pacman -Rns $orphans
else
  echo "• Nessun pacchetto orfano trovato."
fi

echo

if command -v flatpak >/dev/null 2>&1; then
  echo "• Aggiornamento dei pacchetti Flatpak..."
  flatpak update -y
else
  echo "• Flatpak non trovato."
fi

echo

if command -v distrobox >/dev/null 2>&1; then
  echo "• Distrobox trovato."
  distrobox upgrade --all
else
  echo "• Distrobox non trovato."
fi

sh ~/.config/niri/scripts/show-done